### ISSUE TITLE
Add support for ALIBABA_CLOUD_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/alibaba-cloud-csi-driver#557]
It would be nice if the CSI drivers support `ALIBABA_CLOUD_CREDENTIALS_FILE` env. variable, pointing to a file with this format

```
[default]
type = access_key
access_key_id: xxxxxxx
access_key_secret: yyyyy
```

There are some traces of using such env. var + file format in [vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/tree/master/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider), maybe it can be reused.

**Comment by kwoodson** [comment]
@jsafrane I think this has been addressed. Can we close?

**Comment by mowangdk** [comment]
to reuse ```vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider```, a lot of code changes are involved, so we will not support this env for the time being.

**Comment by kwoodson** [comment]
@mowangdk The code that we would like to use is this code here:
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider/profile_credentials.go#L40

Support for reading the INI file format already exists in the code above. 

An example of using this code is here:
```
https://github.com/openshift/cluster-ingress-operator/pull/683/files#diff-70322845158824666344cf3d2576ededa80d36c42e911b4e3f05bb626940ac60R25-R64
```
> to reuse vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider, a lot of code changes are involved, so we will not support this env for the time being.

I don't believe it would take a lot of code changes since the function above is relatively small (64 lines of code). The other issue I see that would make the code easier to consume is to have a way to read the credentials from a file without setting the environment variable. If  Alibaba could add an additional function or refactor the code to have an additional parameter that does not require the environment variable the consumer of these functions could pass a file object to a function which would avoid doing any environment variable setting or locking. 

@gujingit @menglingwei @lyt99 @DahuK @bd233 WDYT?

**Comment by mowangdk** [comment]
> @mowangdk The code that we would like to use is this code here: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/master/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider/profile_credentials.go#L40
> 
> Support for reading the INI file format already exists in the code above.
> 
> An example of using this code is here:
> 
> ```
> https://github.com/openshift/cluster-ingress-operator/pull/683/files#diff-70322845158824666344cf3d2576ededa80d36c42e911b4e3f05bb626940ac60R25-R64
> ```
> 
> > to reuse vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/provider, a lot of code changes are involved, so we will not support this env for the time being.
> 
> I don't believe it would take a lot of code changes since the function above is relatively small (64 lines of code). The other issue I see that would make the code easier to consume is to have a way to read the credentials from a file without setting the environment variable. If Alibaba could add an additional function or refactor the code to have an additional parameter that does not require the environment variable the consumer of these functions could pass a file object to a function which would avoid doing any environment variable setting or locking.
> 
> @gujingit @menglingwei @Lyt99 @DahuK @bd233 WDYT?

what you says did make sense, but the point does not lie in the reading of ini files. We are not use the ```auth.Credential``` interface to generate OpenApi client. this change involves all backing store types. So we need a long period of verification.

**Comment by jsafrane** [comment]
I think this has been fixed by https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/572
/close
